### ISSUE TITLE
Running the server with Podman

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-community/ara-collection#40]
This issue is to investigate if any issues exist to run the ARA server on Podman.

**Comment by dmsimard** [comment]
There is "prior art" for this that we can heavily draw inspiration from -- first, instructions from the quay.io/dockerhub readme:
```
podman run --name ara --detach --tty \
  --volume ~/.ara/server:/opt/ara:z -p 8000:8000 \
  quay.io/recordsansible/ara-api:latest
```

and then for an eventual systemd unit file for the podman container, @mscherer recently shared this piece (thanks!):
```
[Unit]
Wants=network.target
After=network-online.target

[Service]
{% for e in env %}
Environment={{ e }}={{ env[e] }}
{% endfor %}
Restart=on-failure
ExecStartPre=-/usr/bin/podman create --conmon-pidfile=%t/%N.pid  --name=%N {% if network is defined %}--net={{ network }}{% endif %} {% for v in volumes %}-v {{ v.src }}:{{ v.dest }} {% endfor %} --env-host=true --rm {% for p in ports %}-p {{ p.external }}:{{ p.internal }} {% endfor %}{{ image }} {{ command }}
ExecStart=/usr/bin/podman start %N
ExecStop=/usr/bin/podman stop %N
ExecStopPost=/usr/bin/podman rm %N
Type=forking
PIDFile=%t/%N.pid
{% if exit_code is defined %}
SuccessExitStatus={{ exit_code }}
{% endif %}
[Install]
WantedBy=multi-user.target
```

As to how this might work in practice, considering how [ara_api/tasks/main.yaml](https://github.com/ansible-community/ara-collection/blob/master/roles/ara_api/tasks/main.yaml) is structured:
```
- name: Include installation of ARA
  include_tasks: "install/{{ ara_api_install_method }}.yaml"  <--- podman should be an install method

- name: Include configuration of the ARA API
  include_tasks: config.yaml               <--- nothing to do here I think
                                           we still need to template a settings.yaml and mount it to the container

- name: Include configuration of the database engine
  include_tasks: "database_engine/{{ ara_api_database_engine }}.yaml"  <--- This is handled by the container automatically

- name: Include installation of the WSGI backend server
  include_tasks: "wsgi_server/{{ ara_api_wsgi_server }}.yaml"  <--- podman would probably be the wsgi_server since gunicorn ships in the image ?
  when: ara_api_wsgi_server is not none                        it's where we would pull the image and set up a systemd unit

- name: Include installation of the frontend server
  include_role:
    name: "ara_frontend_{{ ara_api_frontend_server }}"   <--- this should not change that much ?
                                                         we're still reverse proxying to 127.0.0.1:8000
  when: ara_api_frontend_server is not none
```
